### ISSUE TITLE
Protected -> Private - Why?

### ISSUE THREAD

**Issue by CarsonF** [hellogerard/jobby#35]
Why were methods changed to private? This only makes Jobby less extendable. I have a couple cases where I've overridden some methods and 2.1 breaks this.

**Comment by hellogerard** [comment]
Ah, that made it in in a [recent PR](f3c4c055e973b698c36af787f973ba06693dd597). I didn't catch that, but I actually agree they should be protected. Easy to revert. 

@SchulteMarkus you made the change. What do you think?

**Comment by SchulteMarkus** [comment]
I assert that every method should be private, if possible. As I saw protected methods, which could have been private, while coding on jobby, I decided to change the visibility of this methods to private.

Well, but this is not the point to discuss programming ideologies. If you need to overwrite methods, change the visibility of this ones to protected, of course. 

Further readings on private/protected, if you are interested: [stackoverflow: Reasons to use private instead of protected for fields and methods](http://stackoverflow.com/a/4913070/1645517), [stackoverflow: Private vs Protected - Visibility Good-Practice Concern](http://stackoverflow.com/a/8353371/1645517)

**Comment by CarsonF** [comment]
I agree that composition over inheritance is better. However, given that Jobby is mostly two classes there is not much to compose. Refactoring to break up these classes would, IMO, warrant a major release (3.0).

**Comment by SchulteMarkus** [comment]
I agree.

**Comment by hellogerard** [comment]
Seems like the best thing in this case is to revert. Going to publish a new release today or tomorrow with this change and the PDO pull request.

**Comment by hellogerard** [comment]
Closed by 33fc6e03a26873263008c4907d5847ab4846319a

**Comment by SchulteMarkus** [comment]
@CarsonF, @hellogerard reverted my commit as agreed. But maybe you can declare in your coming Pull-Request every filed/method as private, where possible, so that the visibility is as private as possible.

**Comment by hellogerard** [comment]
Published [v2.2.0](https://packagist.org/packages/hellogerard/jobby).
